services:
    db:
        image: postgres:alpine
        ports:
            - 5432:5432
        volumes:
            - lbm_dev_data:/var/lib/postgresql/data
        env_file:
            - .env.dev

volumes:
    lbm_dev_data:
        driver: local
