services:
    lbm_db:
        image: postgres:alpine
        volumes:
            - lbm_data:/var/lib/postgresql/data
        env_file:
            - .env.docker
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}",
                ]
            interval: 10s
            retries: 5
            start_period: 30s
            timeout: 10s

    lbm_search:
        image: getmeili/meilisearch:v1.26.0
        volumes:
            - lbm_search_data:/meili_data
        env_file:
            - .env.docker
        depends_on:
            lbm_db:
                condition: service_healthy

    lbm_app:
        build: .
        ports:
            - 80:3000
        env_file:
            - .env.docker
        depends_on:
            lbm_db:
                condition: service_healthy
            lbm_search:
                condition: service_started

volumes:
    lbm_data:
        driver: local
    lbm_search_data:
        driver: local
