services:
    lbm_db:
        image: postgres:alpine
        volumes:
            - lbm_data:/var/lib/postgresql/data
        env_file:
            - .env
    lbm_app:
        build: .
        ports:
            - 3000:3000
        env_file:
            - .env

volumes:
    lbm_data:
        driver: local
