services:
    db:
        image: postgres:alpine
        ports:
            - 5432:5432
        volumes:
            - lbm_dev_data:/var/lib/postgresql/data
        env_file:
            - .env.development

        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}",
                ]
            interval: 10s
            retries: 5
            start_period: 30s
            timeout: 10s

    search:
        container_name: search
        image: getmeili/meilisearch:v1.26.0
        ports:
            - 7700:7700
        volumes:
            - lmb_search_data:/meili_data

        env_file: .env.development

        depends_on:
            db:
                condition: service_healthy

volumes:
    lbm_dev_data:
        driver: local
    lmb_search_data:
        driver: local
