-- AlterEnum
BEGIN;
CREATE TYPE "REPORT_CONTENT_new" AS ENUM ('USER', 'POST', 'REVIEW');
ALTER TABLE "report" ALTER COLUMN "type" TYPE "REPORT_CONTENT_new" USING ("type"::text::"REPORT_CONTENT_new");
ALTER TYPE "REPORT_CONTENT" RENAME TO "REPORT_CONTENT_old";
ALTER TYPE "REPORT_CONTENT_new" RENAME TO "REPORT_CONTENT";
DROP TYPE "public"."REPORT_CONTENT_old";
COMMIT;

-- AlterTable
ALTER TABLE "report" ADD COLUMN     "ratingId" TEXT;

-- AddForeignKey
ALTER TABLE "report" ADD CONSTRAINT "report_ratingId_fkey" FOREIGN KEY ("ratingId") REFERENCES "rating"("id") ON DELETE CASCADE ON UPDATE CASCADE;
